### ISSUE TITLE
关于ai-rate组件

### ISSUE THREAD

**Issue by louisnikai** [yisibell/aidol-questionnaire-ui#10]
可否增加Min配置项？可能需要非从1开始自动生成评分项，例如0,1,2,3,4,5

**Comment by yisibell** [comment]
> 可否增加Min配置项？可能需要非从1开始自动生成评分项，例如0,1,2,3,4,5

已在 `v1.9.0` 中新增。

**Comment by louisnikai** [comment]
感谢更新！
