### ISSUE TITLE
关于ai-rate的一些问题

### ISSUE THREAD

**Issue by louisnikai** [yisibell/aidol-questionnaire-ui#8]
1. Hover时不应把is-active class覆盖掉，要不Hover时没法判断本身选中的是哪个；
2. ai-rate组件能不能提供一种模式选择，可以配置是单个高亮还是选中项之前的都高亮？

**Comment by yisibell** [comment]
> 1. Hover时不应把is-active class覆盖掉，要不Hover时没法判断本身选中的是哪个；
> 2. ai-rate组件能不能提供一种模式选择，可以配置是单个高亮还是选中项之前的都高亮？

`v1.8.0` 已支持。请参看文档：https://hongwenqing.com/aidol-questionnaire-ui/#/rate

**Comment by louisnikai** [comment]
看示例好像还有点问题，hover时高亮的项，鼠标移开后高亮不消失。

**Comment by louisnikai** [comment]
感谢更新！

看示例好像还有点问题，hover时高亮的项，鼠标移开后高亮不消失。

**Comment by yisibell** [comment]
> 看示例好像还有点问题，hover时高亮的项，鼠标移开后高亮不消失。

已在 `v1.8.1` 中修复。

**Comment by louisnikai** [comment]
好的，谢谢更新和修正！
